spring.application.name=gamestore

## Configurar o Banco de Dados 
spring.datasource.url=jdbc:postgresql://dpg-d6tvggn5gffc739dur40-a.oregon-postgres.render.com/db_deploy_gs_gabi0403
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Obs.: Nunca colocar senhas em documentos que vão para o github



## Configurações do JPA - hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect